### ISSUE TITLE
URL server

### ISSUE THREAD

**Issue by CallinDai** [sassoftware/rest-api-use-cases#2]
i am a SAS Viya user ( using the 14 days free trail now), and i was trying to finished the Authentication part. But i do not know what my server URL is and where to type in the first two lines of code to get the token value. 

<img width="679" alt="截屏2023-06-14 下午9 39 55" src="https://github.com/sassoftware/rest-api-use-cases/assets/121204867/d31bf053-294d-4b8b-ae41-f97f7648b997">

It will be great if you can help me out. Thank you!

**Comment by jefurbee** [comment]
Hi CallinDai,
SAS does not currently allow access from external sources (e.g., REST clients) on the SAS Viya trial environments. Hence, you'll not be able register clients or generate access tokens.

To answer your question, you're server URL would be the URL you use to access the SAS Viya GUI interface, e.g., https://mysasviyatrial.sas.com. 

I should also note the trials run the latest LTS version of SAS Viya. The authentication instructions in this repo are for older versions of SAS. I'll work on updating the authentication scripts to provide both versions of code.

You can find a Python version of the new code [here](https://github.com/sassoftware/rest-api-use-cases/tree/main/authentication). Again, I'll work on getting a Postman version published soon.
